version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/jerry1123/async-code-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./async-code-web:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/jerry1123/async-code-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=True
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - claude-automation-build

  claude-automation-build:
    build:
      context: .
      dockerfile: Dockerfile.claude-automation
    image: registry.cn-hangzhou.aliyuncs.com/jerry1123/claude-code-automation:latest
    command: ["echo", "Claude Code automation image built"]

volumes:
  docker_socket:
